#################################################
#
#         SoulCamp
#
# Разработчик: rain_chat
#
# Поддерживает плагины:
# 1. vault
# 2. PlaceholderAPI
#
#################################################
#
# Пример HEX цвета - <#8aafeb>
#
# Доступные плейсхолдеры,
# на данном этапе работает только в этом плагине:
# %scamp_pvp_teg% - пвп тег
# %scamp_getcarma% - очки кармы у игрока
#
##################################################

Settings:
  language: Ru_ru

itemsNoDrop:
  - 0
  - 1
  - 2
  - 3

Carma:
  # Сколько действует пвп режим в секундах
  pvp-mode: 15
  # Тег для проверки игрока на пвп режим, можно вызвать %scamp_pvp_teg%
  pvp-tag:
    pvp: "&e"
    nopvp: ""
  # Максимальная карма у игрока
  max-point: 1000
  # Сколько кармы отнимается при ударе по игроку
  when-hit-player: -1
  # Сколько кармы отнимается при убийстве игрока
  when-kill-player: -15
  # Сколько игрок потеряет предметов при неудачной смерти в %
  drop-percent: 50

  point-tag:
    good:
      color: "1&f"
      save-chance: 0
      points: 1000
    bad:
      color: "&c"
      save-chance: 70
      points: 970
    so_bed:
      color: "&4"
      save-chance: 20
      points: 950
    killer_all:
      color: "&4"
      save-chance: 5
      points: 0